version: '3.8'

services:
  wordpress:
    container_name: wordpress  
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_user_pass
      WORDPRESS_DB_HOST: mysql
    ports:
      - "8083:80"
    volumes:
      ["./wp_data:/var/www/html"]
    networks:
      mysql-phpmyadmin: {}

volumes:
  wp_data:

networks:
  mysql-phpmyadmin:
    external: true